import { Claim } from './claims/claim.model';

export const CLAIM_MOCK_DATA: Claim[] = [
  {
    id: 1,
    policyNumber: 'PN123456',
    dateofLoss: new Date('2024-06-01'),
    causeOfLoss: 'Fire',
    claimAmount: 1200.0,
    status: 'Pending',
    claimType: 'Property',
    customerName: 'John Doe',
    date: ''
  },
  {
    id: 2,
    policyNumber: 'PN123457',
    dateofLoss: new Date('2024-06-02'),
    causeOfLoss: 'Theft',
    claimAmount: 500.0,
    status: 'Approved',
    claimType: 'Auto',
    customerName: 'Jane Smith',
    date: ''
  },
  {
    id: 3,
    policyNumber: 'PN123458',
    dateofLoss: new Date('2024-06-03'),
    causeOfLoss: 'Flood',
    claimAmount: 800.0,
    status: 'Denied',
    claimType: 'Property',
    customerName: 'Alice Johnson',
    date: ''
  },
  {
    id: 4,
    policyNumber: 'PN123459',
    dateofLoss: new Date('2024-06-04'),
    causeOfLoss: 'Accident',
    claimAmount: 700.0,
    status: 'Pending',
    claimType: 'Auto',
    customerName: 'Robert Brown',
    date: ''
  },
  {
    id: 5,
    policyNumber: 'PN123460',
    dateofLoss: new Date('2024-06-05'),
    causeOfLoss: 'Vandalism',
    claimAmount: 900.0,
    status: 'Approved',
    claimType: 'Property',
    customerName: 'Mary White',
    date: ''
  },
  {
    id: 6,
    policyNumber: 'PN123461',
    dateofLoss: new Date('2024-06-06'),
    causeOfLoss: 'Fire',
    claimAmount: 1100.0,
    status: 'Pending',
    claimType: 'Property',
    customerName: 'James Green',
    date: ''
  },
  {
    id: 7,
    policyNumber: 'PN123462',
    dateofLoss: new Date('2024-06-07'),
    causeOfLoss: 'Theft',
    claimAmount: 600.0,
    status: 'Approved',
    claimType: 'Auto',
    customerName: 'Patricia Black',
    date: ''
  },
  {
    id: 8,
    policyNumber: 'PN123463',
    dateofLoss: new Date('2024-06-08'),
    causeOfLoss: 'Flood',
    claimAmount: 700.0,
    status: 'Denied',
    claimType: 'Property',
    customerName: 'Christopher Gray',
    date: ''
  },
  {
    id: 9,
    policyNumber: 'PN123464',
    dateofLoss: new Date('2024-06-09'),
    causeOfLoss: 'Accident',
    claimAmount: 800.0,
    status: 'Pending',
    claimType: 'Auto',
    customerName: 'Linda Blue',
    date: ''
  },
  {
    id: 10,
    policyNumber: 'PN123465',
    dateofLoss: new Date('2024-06-10'),
    causeOfLoss: 'Vandalism',
    claimAmount: 900.0,
    status: 'Approved',
    claimType: 'Property',
    customerName: 'David Brown',
    date: ''
  },
  {
    id: 11,
    policyNumber: 'PN123466',
    dateofLoss: new Date('2024-06-11'),
    causeOfLoss: 'Fire',
    claimAmount: 1200.0,
    status: 'Pending',
    claimType: 'Property',
    customerName: 'Sarah Yellow',
    date: ''
  },
  {
    id: 12,
    policyNumber: 'PN123467',
    dateofLoss: new Date('2024-06-12'),
    causeOfLoss: 'Theft',
    claimAmount: 500.0,
    status: 'Approved',
    claimType: 'Auto',
    customerName: 'Michael Red',
    date: ''
  },
  {
    id: 13,
    policyNumber: 'PN123468',
    dateofLoss: new Date('2024-06-13'),
    causeOfLoss: 'Flood',
    claimAmount: 800.0,
    status: 'Denied',
    claimType: 'Property',
    customerName: 'Laura White',
    date: ''
  },
  {
    id: 14,
    policyNumber: 'PN123469',
    dateofLoss: new Date('2024-06-14'),
    causeOfLoss: 'Accident',
    claimAmount: 700.0,
    status: 'Pending',
    claimType: 'Auto',
    customerName: 'Anthony Orange',
    date: ''
  },
  {
    id: 15,
    policyNumber: 'PN123470',
    dateofLoss: new Date('2024-06-15'),
    causeOfLoss: 'Vandalism',
    claimAmount: 900.0,
    status: 'Approved',
    claimType: 'Property',
    customerName: 'Barbara Pink',
    date: ''
  },
  {
    id: 16,
    policyNumber: 'PN123471',
    dateofLoss: new Date('2024-06-16'),
    causeOfLoss: 'Fire',
    claimAmount: 1100.0,
    status: 'Pending',
    claimType: 'Property',
    customerName: 'Richard Purple',
    date: ''
  },
  {
    id: 17,
    policyNumber: 'PN123472',
    dateofLoss: new Date('2024-06-17'),
    causeOfLoss: 'Theft',
    claimAmount: 600.0,
    status: 'Approved',
    claimType: 'Auto',
    customerName: 'Jessica Gold',
    date: ''
  },
  {
    id: 18,
    policyNumber: 'PN123473',
    dateofLoss: new Date('2024-06-18'),
    causeOfLoss: 'Flood',
    claimAmount: 700.0,
    status: 'Denied',
    claimType: 'Property',
    customerName: 'Mark Silver',
    date: ''
  },
  {
    id: 19,
    policyNumber: 'PN123474',
    dateofLoss: new Date('2024-06-19'),
    causeOfLoss: 'Accident',
    claimAmount: 800.0,
    status: 'Pending',
    claimType: 'Auto',
    customerName: 'Emily Bronze',
    date: ''
  },
  {
    id: 20,
    policyNumber: 'PN123475',
    dateofLoss: new Date('2024-06-20'),
    causeOfLoss: 'Vandalism',
    claimAmount: 900.0,
    status: 'Approved',
    claimType: 'Property',
    customerName: 'Daniel Green',
    date: ''
  },
  {
    id: 21,
    policyNumber: 'PN123476',
    dateofLoss: new Date('2024-06-21'),
    causeOfLoss: 'Fire',
    claimAmount: 1200.0,
    status: 'Pending',
    claimType: 'Property',
    customerName: 'Angela Blue',
    date: ''
  },
  {
    id: 22,
    policyNumber: 'PN123477',
    dateofLoss: new Date('2024-06-22'),
    causeOfLoss: 'Theft',
    claimAmount: 500.0,
    status: 'Approved',
    claimType: 'Auto',
    customerName: 'Ryan Black',
    date: ''
  },
  {
    id: 23,
    policyNumber: 'PN123478',
    dateofLoss: new Date('2024-06-23'),
    causeOfLoss: 'Flood',
    claimAmount: 800.0,
    status: 'Denied',
    claimType: 'Property',
    customerName: 'Sharon Pink',
    date: ''
  },
  {
    id: 24,
    policyNumber: 'PN123479',
    dateofLoss: new Date('2024-06-24'),
    causeOfLoss: 'Accident',
    claimAmount: 700.0,
    status: 'Pending',
    claimType: 'Auto',
    customerName: 'Gregory White',
    date: ''
  },
  {
    id: 25,
    policyNumber: 'PN123480',
    dateofLoss: new Date('2024-06-25'),
    causeOfLoss: 'Vandalism',
    claimAmount: 900.0,
    status: 'Approved',
    claimType: 'Property',
    customerName: 'Jennifer Brown',
    date: ''
  },
  {
    id: 26,
    policyNumber: 'PN123481',
    dateofLoss: new Date('2024-06-26'),
    causeOfLoss: 'Fire',
    claimAmount: 1100.0,
    status: 'Pending',
    claimType: 'Property',
    customerName: 'Steven Green',
    date: ''
  },
  {
    id: 27,
    policyNumber: 'PN123482',
    dateofLoss: new Date('2024-06-27'),
    causeOfLoss: 'Theft',
    claimAmount: 600.0,
    status: 'Approved',
    claimType: 'Auto',
    customerName: 'Patricia Black',
    date: ''
  },
  {
    id: 28,
    policyNumber: 'PN123483',
    dateofLoss: new Date('2024-06-28'),
    causeOfLoss: 'Flood',
    claimAmount: 700.0,
    status: 'Denied',
    claimType: 'Property',
    customerName: 'Gregory White',
    date: ''
  },
  {
    id: 29,
    policyNumber: 'PN123484',
    dateofLoss: new Date('2024-06-29'),
    causeOfLoss: 'Accident',
    claimAmount: 800.0,
    status: 'Pending',
    claimType: 'Auto',
    customerName: 'Peter Crouch',
    date: ''
  },
  {
    id: 30,
    policyNumber: 'PN123485',
    dateofLoss: new Date('2024-06-30'),
    causeOfLoss: 'Vandalism',
    claimAmount: 900.0,
    status: 'Approved',
    claimType: 'Property',
    customerName: 'Gregory White',
    date: ''
  },
];
